steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/diffbind:${SHORT_SHA}', '.']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/diffbind', '.']
images:
- gcr.io/${PROJECT_ID}/diffbind:${SHORT_SHA}
- gcr.io/${PROJECT_ID}/diffbind
