substitutions:
  _GCR_REGISTRY: us.gcr.io
  _IMAGE_NAME: epi-diffbind

steps:
# Use a fixed Kaniko build, until GoogleContainerTools/kaniko#1039 fix is in stable
- name: gcr.io/kaniko-project/executor:a1af057f997316bfb1c4d2d82719d78481a02a79
  args:
  - --destination=${_GCR_REGISTRY}/${PROJECT_ID}/${_IMAGE_NAME}
  - --cache=true

timeout: 5400s
