timeout: 30m
steps:
- name: gcr.io/cloud-builders/docker
  args: ['pull', 'us.gcr.io/${PROJECT_ID}/diffbind']
- name: gcr.io/cloud-builders/docker
  args: ['build', '--cache-from', 'us.gcr.io/${PROJECT_ID}/diffbind', '-t', 'us.gcr.io/${PROJECT_ID}/diffbind:${SHORT_SHA}', '.']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'us.gcr.io/${PROJECT_ID}/diffbind', '.']
images:
- us.gcr.io/${PROJECT_ID}/diffbind:${SHORT_SHA}
- us.gcr.io/${PROJECT_ID}/diffbind
